In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('call_activity.csv')
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [10]:
type(df)

pandas.core.frame.DataFrame

In [13]:
type(df['State'])

pandas.core.series.Series

In [12]:
df['State']

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [9]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [8]:
df.tail(56)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3277,OK,134,415,No,No,0,164.9,115.0,28.03,126.5,96.0,10.75,238.5,125.0,10.73,10.0,9,2.70,2.0,False
3278,WI,87,415,No,No,0,238.0,97.0,40.46,164.5,97.0,13.98,282.5,132.0,12.71,10.6,6,2.86,2.0,False
3279,NJ,139,415,No,Yes,43,231.0,85.0,39.27,222.3,82.0,18.90,148.0,105.0,6.66,8.3,5,2.24,2.0,False
3280,AR,76,408,No,No,0,107.3,140.0,18.24,238.2,133.0,20.25,271.8,116.0,12.23,10.0,3,2.70,4.0,True
3281,UT,100,408,No,No,0,185.0,122.0,31.45,182.5,92.0,15.51,274.9,92.0,12.37,5.1,8,1.38,1.0,False
3282,DC,99,415,No,Yes,31,244.1,71.0,41.50,203.4,58.0,17.29,234.0,115.0,10.53,7.7,4,2.08,3.0,False
3283,AK,99,510,No,No,0,238.4,96.0,40.53,246.5,130.0,20.95,198.4,117.0,8.93,12.4,4,3.35,3.0,False
3284,AZ,48,415,No,Yes,27,141.1,109.0,23.99,224.7,94.0,19.10,174.3,122.0,7.84,13.2,2,3.56,1.0,False
3285,KS,57,415,No,No,0,158.1,117.0,26.88,115.2,149.0,9.79,182.4,92.0,8.21,11.8,7,3.19,0.0,False
3286,OH,106,415,No,Yes,30,220.1,105.0,37.42,222.2,109.0,18.89,158.4,96.0,7.13,13.1,8,3.54,0.0,False
3287,KS,170,415,No,Yes,42,199.5,119.0,33.92,135.0,90.0,11.48,184.6,49.0,8.31,10.9,3,2.94,4.0,True
3288,SC,78,415,No,No,0,109.5,105.0,18.62,286.1,90.0,24.32,247.6,113.0,11.14,4.9,9,1.32,1.0,False
3289,TN,39,408,No,No,0,187.2,110.0,31.82,114.7,116.0,9.75,104.7,83.0,4.71,13.2,5,3.56,1.0,False
3290,CA,127,510,No,No,0,107.9,128.0,18.34,187.0,77.0,15.90,218.5,95.0,9.83,0.0,0,0.00,0.0,False
3291,MI,119,510,Yes,Yes,22,172.1,119.0,29.26,223.6,133.0,19.01,150.0,94.0,6.75,13.9,20,3.75,1.0,True
3292,IN,114,408,No,No,0,203.8,85.0,34.65,87.8,110.0,7.46,166.2,122.0,7.48,11.7,4,3.16,1.0,False
3293,RI,95,408,No,No,0,160.0,133.0,27.20,215.3,98.0,18.30,188.9,87.0,8.50,9.1,4,2.46,0.0,False
3294,MO,116,408,No,No,0,51.1,106.0,8.69,208.6,137.0,17.73,198.0,92.0,8.91,12.3,3,3.32,1.0,False
3295,TN,110,415,No,No,0,227.7,88.0,38.71,170.0,96.0,14.45,128.7,57.0,5.79,11.7,5,3.16,1.0,False
3296,CT,74,510,No,No,0,203.8,77.0,34.65,205.1,111.0,17.43,154.9,109.0,6.97,9.0,2,2.43,1.0,False
3297,ME,148,408,No,Yes,33,241.7,84.0,41.09,165.8,84.0,14.09,160.6,80.0,7.23,11.3,3,3.05,1.0,False
3298,MD,83,510,No,No,0,78.1,70.0,13.28,239.3,115.0,20.34,144.4,112.0,6.50,12.3,4,3.32,1.0,False
3299,NC,73,408,No,No,0,187.8,95.0,31.93,149.2,143.0,12.68,201.4,113.0,9.06,11.0,4,2.97,2.0,False
3300,SC,111,415,No,Yes,21,127.1,94.0,21.61,228.3,116.0,19.41,166.7,108.0,7.50,7.1,3,1.92,1.0,False
3301,CA,84,415,No,No,0,280.0,113.0,47.60,202.2,90.0,17.19,156.8,103.0,7.06,10.4,4,2.81,0.0,True
3302,LA,75,510,Yes,No,0,153.2,78.0,26.04,210.8,99.0,17.92,153.5,100.0,6.91,7.8,3,2.11,1.0,False
3303,WI,114,415,No,Yes,26,137.1,88.0,23.31,155.7,125.0,13.23,247.6,94.0,11.14,11.5,7,3.11,2.0,False
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3305,IN,58,415,No,Yes,22,224.1,127.0,38.10,238.8,85.0,20.30,174.2,86.0,7.84,11.5,7,3.11,2.0,False
3306,AL,106,408,No,Yes,29,83.6,131.0,14.21,203.9,131.0,17.33,229.5,73.0,10.33,8.1,3,2.19,1.0,False
3307,OK,172,408,No,No,0,203.9,109.0,34.66,234.0,123.0,19.89,160.7,65.0,7.23,17.8,4,4.81,4.0,False
3308,IA,45,415,No,No,0,211.3,87.0,35.92,165.7,97.0,14.08,265.9,72.0,11.97,13.3,6,3.59,1.0,False
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3310,NY,94,415,No,No,0,190.4,91.0,32.37,92.0,107.0,7.82,224.8,108.0,10.12,13.6,17,3.67,2.0,False
3311,LA,128,415,No,No,0,147.7,94.0,25.11,283.3,83.0,24.08,188.3,124.0,8.47,6.9,5,1.86,2.0,False
3312,SC,181,408,No,No,0,229.9,130.0,39.08,144.4,93.0,12.27,262.4,110.0,11.81,14.2,4,3.83,2.0,False
3313,ID,127,408,No,No,0,102.8,128.0,17.48,143.7,95.0,12.21,191.4,97.0,8.61,10.0,5,2.70,1.0,False
3314,MO,89,415,No,No,0,178.7,81.0,30.38,233.7,74.0,19.86,131.9,120.0,5.94,9.1,4,2.46,1.0,False
3315,ME,149,415,No,Yes,18,148.5,106.0,25.25,114.5,106.0,9.73,178.3,98.0,8.02,6.5,4,1.76,0.0,False
3316,MS,103,510,No,Yes,29,164.1,111.0,27.90,219.1,96.0,18.62,220.3,108.0,9.91,12.3,9,3.32,0.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3318,OK,52,415,No,No,0,124.9,131.0,21.23,300.5,118.0,25.54,192.5,106.0,8.66,11.6,4,3.13,2.0,False
3319,WY,89,415,No,No,0,115.4,99.0,19.62,209.9,115.0,17.84,280.9,112.0,12.64,15.9,6,4.29,3.0,False
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True
3321,VT,60,415,No,No,0,193.9,118.0,32.96,85.0,110.0,7.23,210.1,134.0,9.45,13.2,8,3.56,3.0,False
3322,MD,62,408,No,No,0,321.1,105.0,54.59,265.5,122.0,22.57,180.5,72.0,8.12,11.5,2,3.11,4.0,True
3323,IN,117,415,No,No,0,118.4,126.0,20.13,249.3,97.0,21.19,227.0,56.0,10.22,13.6,3,3.67,5.0,True
3324,WV,159,415,No,No,0,169.8,114.0,28.87,197.7,105.0,16.80,193.7,82.0,8.72,11.6,4,3.13,1.0,False
3325,OH,78,408,No,No,0,193.4,99.0,32.88,116.9,88.0,9.94,243.3,109.0,10.95,9.3,4,2.51,2.0,False
3326,OH,96,415,No,No,0,106.6,128.0,18.12,284.8,87.0,24.21,178.9,92.0,8.05,14.9,7,4.02,1.0,False
3327,SC,79,415,No,No,0,134.7,98.0,22.90,189.7,68.0,16.12,221.4,128.0,9.96,11.8,5,3.19,2.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

## Creat a dataframe from a dictionary

In [18]:
temp={

    'Name':['John','Mike','robert'],
    'Designation':['Engineer','clerk','Press'],
    'Salary':[20000000,30000,456665]
}
dict=pd.DataFrame.from_dict(temp)
dict

     Name Designation    Salary
0    John    Engineer  20000000
1    Mike       clerk     30000
2  robert       Press    456665

In [19]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [21]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [22]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [24]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [27]:
df['International plan']

0        No
1        No
2        No
3       Yes
4       Yes
       ...
3328     No
3329     No
3330     No
3331    Yes
3332     No
Name: International plan, Length: 3333, dtype: object

In [29]:
df[['International plan','Total day calls','Total eve minutes' ] ]

     International plan  Total day calls  Total eve minutes
0                    No            110.0              197.4
1                    No            123.0              195.5
2                    No            114.0              121.2
3                   Yes             71.0               61.9
4                   Yes            113.0              148.3
...                 ...              ...                ...
3328                 No             77.0              215.5
3329                 No             57.0              153.4
3330                 No            109.0              288.8
3331                Yes            105.0              159.6
3332                 No            113.0              265.9

[3333 rows x 3 columns]

In [5]:
df.State.unique()

NameError: name 'df' is not defined

In [34]:
df[df['International plan']=='Yes']

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False

In [11]:
df[(df['International plan']=='Yes') & (df['Churn']==False)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,WV,117,510,Yes,No,0,198.4,121.0,33.73,249.5,104.0,21.21,162.8,115.0,7.33,10.5,5,2.84,1.0,False
3302,LA,75,510,Yes,No,0,153.2,78.0,26.04,210.8,99.0,17.92,153.5,100.0,6.91,7.8,3,2.11,1.0,False
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False

In [12]:
df.head(20)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [14]:
df.head(15)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False

In [18]:
df.iloc[14]

State                        IA
Account length               62
Area code                   415
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         307.2
Total eve calls            76.0
Total eve charge          26.11
Total night minutes       203.0
Total night calls          99.0
Total night charge         9.14
Total intl minutes         13.1
Total intl calls              6
Total intl charge          3.54
Customer service calls      4.0
Churn                     False
Name: 14, dtype: object

In [19]:
df.iloc[14,1] #row,column

np.int64(62)

In [20]:
df.iloc[14,-1]

False

#slicing

In [21]:
df.iloc[9: 20]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False